version: "3.8"
services:
  mongodb:
    image: mongo:latest  
    restart: unless-stopped  # Restart container automatically on failures
    environment:
      MONGODB_DB: airlines
      MONGODB_USER: your_user
      MONGODB_PASSWORD: your_password
    ports:
      - 27017:27017
    volumes:
      - ./data_modeling/mongo/:/docker-entrypoint-initdb.d/				

  api:
    build: 
      context: .  
      dockerfile: ./api/Dockerfile
    container_name: api  

    depends_on:
      - mongodb  
    volumes:
      - ./data_collection/scripts/:/app/scripts/
      - ./data_collection/collected_data/:/app/collected_data/
    environment:
      DATABASE_URL: mongodb://your_user:your_password@mongodb:27017/airlines
    command: python /app/scripts/mongo.py


